#!/usr/local/bin/bash

coord_id=$1
user=`whoami`

if [[ "$coord_id" == "" ]]; then
    coord_ids=`oozieclient.pl -r share/oozie/app.yaml jobs -jobtype coord -filter user=$user\;status=RUNNING\;status=RUNNINGWITHERROR | grep yamp- | grep -v Matched | awk '{print $16}'` 
    for coord_id in $coord_ids; do
        oozieclient.pl -r share/oozie/app.yaml job -kill $coord_id -y 
    done
else
    oozieclient.pl -r share/oozie/app.yaml job -kill $coord_id -y 
fi

